<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>


<ul class="style">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="style__item">
            <?php if ($filterItem->getCount() > 0): ?>
                <form class="style__form">
                  <label class="style__label active">
                    <input class="style__checkbox" type="checkbox" name="#" value="yes">

                    
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>

                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    

                    <span class="style__count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                    <?php if ($filterItem->getCount() == 1):?> <?php /* @escapeNotVerified */ echo __('item')?><?php else:?> <?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </label>
            <?php else:?>
                <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?php /* @escapeNotVerified */ echo __('item')?><?php else:?><?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                          </form>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ul>