<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="breadcrumbs">
    <ul class="breadcrumbs__list items">
        <li class="breadcrumbs__item">
            <a class="breadcrumbs__link" id="breadcrumbs-back" href="javascript:history.go(-1)">Back</a>
        </li>
        <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
        <li class="breadcrumbs__item item <?= $block->escapeHtmlAttr($crumbName) ?>">
            <?php if ($crumbInfo['first']) : ?>
            <a
                class="breadcrumbs__link"
                id="breadcrumbs-link"
                href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                <svg
                    class="breadcrumbs__icon-home"
                    version="1.1"
                    xmlns="http://www.w3.org/2000/svg"
                    width="32"
                    height="32"
                    viewbox="0 0 32 32">
                    <title>home2</title>
                    <path
                        d="M16 1l-16 16 3 3 3-3v13h8v-6h4v6h8v-13l3 3 3-3-16-16zM16 14c-1.105 0-2-0.895-2-2s0.895-2 2-2c1.105 0 2 0.895 2 2s-0.895 2-2 2z"></path>
                </svg>
            </a>
        <?php elseif ($crumbInfo['link'] || $crumbInfo['last']) : ?>
            <a
                class="breadcrumbs__link"
                id="breadcrumbs-link"
                href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                <?= $block->escapeHtml($crumbInfo['label']) ?>
            </a>

            <?php endif; ?>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>