<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>
<nav class="navigation" data-action="navigation">
    <ul
        class="top-menu__list"
        data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @noEscape */ $_menuHtml?>
    </ul>

    <ul class="navigation-new__list">
        <li class="navigation-new__item">
            <a class="navigation-new__link" href="#">Zakelijk</a>
        </li>

        <li class="navigation-new__item">
            <a class="navigation-new__link" href="#">Cadeaukaart</a>
        </li>

        <li class="navigation-new__item">
            <a class="navigation-new__link" href="#">Bestelstatus</a>
        </li>

        <li class="navigation-new__item">
            <a class="navigation-new__link" href="#">Klantenservice</a>
        </li>
        <?= $block->getChildHtml() ?>
    </ul>
</nav>

<div class="under-navigation">
    <div class="container">
        <div class="under-navigation__inner">
            <ul class="under-navigation__list">
                <li class="under-navigation__item">
                    <a class="under-navigation__link">
                        Bollebozen Letterpretpakket
                    </a>
                </li>

                <li class="under-navigation__item">
                    <a class="under-navigation__link">
                        Pride
                    </a>
                </li>

                <li class="under-navigation__item">
                    <a class="under-navigation__link">
                        Elektronica Acties
                    </a>
                </li>

                <li class="under-navigation__item">
                    <a class="under-navigation__link">
                        Alles voor je vakantie
                    </a>
                </li>
            </ul>

            <div class="under-navigation__right">
                <a class="under-navigation__link-deel">
                    Alles voor je vakantie
                </a>
            </div>
        </div>
    </div>
</div>