<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
// $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>

<div class="catalogue-products__box-top">
  <div class="catalogue-products__inner-text">
      <h2 class="catalogue-products__title">Muziek op Dvd's en Blu-rays</h2>
      <h3 class="catalogue-products__subtitle">Welkom in de grootste muziekwinkel van de Benelux. Voor alle muziek op dvd en blu-ray ben je bij ons aan het goede adres. Samen op tour met jouw favoriete band of meezingen op een live concert van jouw idool voor de televisie, het kan allemaal! We bieden zowel de laatste albums als het eerste materiaal van je favoriete artiesten aan. Daarbij proberen we ook zo veel mogelijk muziek en live concerts van kleinere bands en singer-songwriters aan te bieden.
        <p class="catalogue-products__text">
        Bekijk ook:
      <a class="catalogue-products__text-button">Top 10 Muziek op Dvd's en Blu-rays</a>
      </p>
      </h3>
</div>
</div>

<?php if (!$_productCollection->count()): ?>
<div class="message info empty">
    <div>
    <?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>    
    <div class="catalogue-products__wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ul class="catalogue-products__list">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php $product_counter=0; ?>
            <?php foreach ($_productCollection as $_product): ?>

                <li class="catalogue-products__item">
                    <div class="catalogue-products__info"
                         id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                         data-container="product-<?= /* @noEscape */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = 'left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;';
                        }
                        ?>

                      <div class="catalogue-products__box-image">
                        <?php // Product Image ?>
                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                           class="catalogue-products__photo"
                           tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>

                        <!-- Add TO COMPARE -->
                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                        <div class="catalogue-products__button-compare">
                            <a href="#"
                               class="action tocompare"
                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
                      <label class="catalogue-products__compare-label">

                          <span
                              class="catalogue-products__compare-checkbox"
                              id="catalogue-products__compare-checkbox-<?= /* @noEscape */ $_product->getId()?>">
                            </span>
                            <span class="compare-products__compare-text"><?php /* @escapeNotVerified */ echo __('Vergelijk met andere artikelen') ?></span>
                          
                      </label>
    </a>
</div>
<!-- Add TO COMPARE -->
</div>

<div class="catalogue-products__box-descr">
<div class="catalogue-products__descr-inner">
    <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
    <a class="catalogue-products__name">
        <p
            class="catalogue-products__text a-btn"
            href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
            <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
        </p>
        <p class="catalogue-products__link a-btn">
            <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
        </p>
    </a>

    <!-- Review -->
    <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
    <!-- Review -->

    <div class="catalogue-products__text-more">
        <div
            class="catalogue-products__description product description product-item-description">
            <?php echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getDescription(), 'description') ?>
            <?= /* @noEscape */ $_helper->productAttribute(
            $_product,
            $_product->getShortDescription(),
            'short_description'
        ) ?>
        </div>
        <a
            class="action more catalogue-products__button-more a-btn"
            href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
            title="<?= /* @noEscape */ $_productNameStripped ?>"><?= $escaper->escapeHtml(__('Meer')) ?>
        </a>
    </div>

    <!-- Products characteristics -->
    <?= $block->getProductDetailsHtml($_product) ?>
    <!-- Products characteristics -->
</div>

<div class="product-item-inner">
    <div class="catalogue-products__box">
        <div class="catalogue-products__box3">

            <?php if ($_product->isSaleable()):?>
            <?php $postParams = $block->getAddToCartPostParams($_product); ?>

            <?= /* @noEscape */ $block->getProductPrice($_product) ?>

            <form
                class="catalogue-products__form"
                data-role="tocart-form"
                data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                method="post">
                <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?>

                <?= $block->getBlockHtml('formkey') ?>

                <!-- some text -->
                <?php if ($product_counter % 3 == 0): ?>
                <span class="catalogue-products__some-text">SUPER PRODUCT</span>

                <?php
                                                    $product_counter++
                                                    ?>
                <?php endif; ?>
                <!-- some text -->
                <div class="catalogue-products__btn">
                    <button
                        type="submit"
                        title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                        class="catalogue-products__button-cart action tocart primary"
                        disabled="disabled">
                        <svg
                            class="catalogue-products__cart-icon"
                            version="1.1"
                            xmlns="http://www.w3.org/2000/svg"
                            width="32"
                            height="32"
                            viewbox="0 0 32 32">
                            <title>cart</title>
                            <path
                                d="M12 29c0 1.657-1.343 3-3 3s-3-1.343-3-3c0-1.657 1.343-3 3-3s3 1.343 3 3z"></path>
                            <path
                                d="M32 29c0 1.657-1.343 3-3 3s-3-1.343-3-3c0-1.657 1.343-3 3-3s3 1.343 3 3z"></path>
                            <path
                                d="M32 16v-12h-24c0-1.105-0.895-2-2-2h-6v2h4l1.502 12.877c-0.915 0.733-1.502 1.859-1.502 3.123 0 2.209 1.791 4 4 4h24v-2h-24c-1.105 0-2-0.895-2-2 0-0.007 0-0.014 0-0.020l26-3.98z"></path>
                        </svg>
                    </button>

                    <?php $wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data'); ?>
                    <ul class="catalogue-products_wishlist-list">
                        <li class="catalogue-products__wishlist-item" data-bind="scope: 'wishlist'">
                            <a
                                class="catalogue-products__wishlist-link"
                                href="#"
                                title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                data-action="add-to-wishlist"
                                role="button">
                                <svg
                                    class="catalogue-products__wish-icon"
                                    version="1.1"
                                    xmlns="http://www.w3.org/2000/svg"
                                    width="32"
                                    height="32"
                                    viewbox="0 0 32 32">
                                    <title>heart</title>
                                    <path
                                        d="M23.6 2c-3.363 0-6.258 2.736-7.599 5.594-1.342-2.858-4.237-5.594-7.601-5.594-4.637 0-8.4 3.764-8.4 8.401 0 9.433 9.516 11.906 16.001 21.232 6.13-9.268 15.999-12.1 15.999-21.232 0-4.637-3.763-8.401-8.4-8.401z"></path>
                                </svg>
                            </a>
                        </a>
                    </li>
                </ul>
            </div>
        </form>
    <?php else:?>
        <?php if ($_product->isAvailable()):?>
        <div class="stock available">
            <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
    <?php else:?>
        <div class="stock unavailable">
            <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
        <?php endif; ?>
        <?php endif; ?>
    </div>

    <?= ($pos && strpos($pos, $viewMode . '-primary')) ?
                                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                            $position,
                                            'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                        ) : '' ?>

    <?= ($pos && strpos($pos, $viewMode . '-secondary')) ?
                                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                            $position,
                                            'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                        ) : '' ?>
</div>

</div>
</div>
</div>
<?= ($pos && strpos($pos, $viewMode . '-actions')) ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
</li>
<?php $product_counter++; ?>
<?php endforeach; ?>
</ul>
</div>

<?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
<script type="text/x-magento-init">
{
"[data-role=tocart-form], .form.map.checkout": {
"catalogAddToCart": {
"product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
}
}
}
</script>
<?php endif; ?>