<?php
/**
 * Copyright © Elogic. All rights reserved.
 * See https://elogic.co for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>

<ul class="authorization__list" >
    <li
        class="link authorization-link"
        data-label="<?= $escaper->escapeHtml(__('or')) ?>">
        <a href="#">
          Inloggen
        </a>
    </li>
</ul>
