<?php
/**
 * Copyright © Elogic. All rights reserved.
 * See https://elogic.co for license details.
 */
?>

<?php /** @var $block \Magento\Framework\Pricing\Render\Amount */ ?>

<span class="price-container <?= $block->escapeHtmlAttr($block->getAdjustmentCssClasses()) ?>"
    <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>
    <?php if ($block->getDisplayLabel() != 'As low as') : ?>
        <?php if ($block->getDisplayLabel()) : ?>
            <span class="price-label"><?= $block->escapeHtml($block->getDisplayLabel()) ?></span>
        <?php endif; ?>
    <?php endif; ?>
    <?php
    $priceseparator = explode(',', $block->formatCurrency($block->getDisplayValue()));
    $dollars = $priceseparator[0];
    $cents = $priceseparator[1];
    $signDollar = '$';
    $zeroCent = '00';
    ?>
    <span class="price-dollars">
      <?php
      echo $dollars . ","
      ?>
        <?php if (strpos($dollars, $signDollar) == true) {
            echo str_replace("$", "", $dollars);
        } ?>
        <?php if (strpos($cents, $zeroCent) == false): ?>
            <sup class="price-cnt">-</sup>
        <?php else: ?>
            <sup class="price-cnt"><?php echo $cents ?></sup>
        <?php endif; ?>
    </span>

    <?php if ($block->hasAdjustmentsHtml()) : ?>
        <?= $block->getAdjustmentsHtml() ?>
    <?php endif; ?>

    <?php if ($block->getSchema()) : ?>
        <meta itemprop="price" content="<?= $block->escapeHtmlAttr($block->getDisplayValue()) ?>"/>
        <meta itemprop="priceCurrency" content="<?= $block->escapeHtmlAttr($block->getDisplayCurrencyCode()) ?>"/>
    <?php endif; ?>
</span>
