<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>

<?php if (count($this->getStores()) > 1): ?>

    <div class="language__wrapper" id="langs-wrapper">
        <div class="language__box" onclick="clickButton()">
            <?php foreach ($this->getStores() as $_lang): ?>
                <?php if ($_lang->getId() == $block->getCurrentStoreId()) : ?>
                    <li class="language__item">
                        <button class="language__button">
                            <img
                                class="language__image"
                                src="<?php echo $this->getViewFileUrl('images/flags/flag_' . $_lang->getCode() . '.png'); ?>"
                                alt="<?php echo 'could not find image for ' . $_lang->getName() ?>"/>
                            <p class="language__text">
                                <?= $block->escapeHtml($_lang->getName()) ?>
                            </p>
                        </button>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="modal" id="myModal">
        <div class="language-popup" id="language-popup">
            <?php foreach ($this->getStores() as $_lang): ?>
                <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
            <a
                class="language-popup__link"
                href="<?php echo $this->getCurrentUrl() . '?___store=' . $_lang->getCode(); ?>">
                <option class="language-popup__text"
                        value="<?php echo $_lang->getCurrentUrl() ?>"
                    <?php echo $_selected ?>><?php echo $this->escapeHtml($_lang->getName()) ?></option>
                <?php if ($_lang->getCode() != 'default'): ?>
                    <img
                        class="language-popup__image"
                        src="<?php echo $this->getViewFileUrl('images/flags/flag_' . $_lang->getCode() . '.png'); ?>"
                        alt="<?php echo 'could not find image for ' . $_lang->getName() ?>"/></a>

                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
