<?php
/**
 * Copyright © Elogic. All rights reserved.
 * See https://elogic.co for license details.
 */
?>
<div class="all-offers">
    <div class="container">
        <ul class="all-offers__list">

            <li class="all-offers__item">
                <a class="all-offers__link">

                    <div class="all-offers__content">
                        <h2 class="all-offers__title">Alle aanbiedingen
                        </h2>
                        <h3 class="all-offers__subtitle">op een rij</h3>
                        
                        <button class="all-offers__button button">></button>
                    </div>


                </a>
            </li>

            <li class="all-offers__item">
                <a class="all-offers__link">

                <div class="all-offers__image" />

                </a>
            </li>
        </ul>

    </div>
</div>