<div class="banners">
    <div class="container">
        <ul class="banners__list">

            <li class="banners__item banners__item--1">
                <a class="banners__link">

                    <h2 class="banners__title">Dagdeal
                    </h2>

                    <div class="banners__wrapper">
                        <div class="banners__image banners__image--1"></div>

                        <div class="banners__content">
                            <h3 class="banners__subtitle banners__subtitle--1">Tot 30% korting op diervoeding & dierbenodigdheden*</h3>
                            <button class="banners__button banners__button--1" id="banners__btn">Naar de actie</button>
                        </div>
                    </div>

                </a>
            </li>

            <li class="banners__item banners__item--2">
                <a class="banners__link">

                    <div class="banners__wrapper">

                        <div class="banners__content banners__content--2">
                            <h3 class="banners__subtitle banners__subtitle--2">Hoge korting op</h3>
                            <p class="banners__text">rugzakken en tassen</p>
                            <button class="banners__button banners__button--2 button">
                                <span class="banners__arrow blocks-promo__arrow">></span>
                            </button>
                        </div>

                        <div class="banners__image banners__image--2"></div>

                    </div>

                </a>
            </li>
        </ul>

    </div>
</div>