<?php
/**
 * Copyright © Elogic. All rights reserved.
 * See https://elogic.co for license details.
 */
?>
<div class="banners">
    <div class="container">
        <ul class="banners__list">

            <li class="banners__item banners__item--1">
                <a class="banners__link">

                    <h2 class="banners__title">Dagdeal
                      <p id="demo"></p>
                    </h2>

                    <div class="banners__wrapper">
                        <div class="banners__image banners__image--1"></div>

                        <div class="banners__content">
                            <h3 class="banners__subtitle banners__subtitle--1">Tot 30% korting op diervoeding & dierbenodigdheden*</h3>
                            <button class="banners__button banners__button--1" id="banners__btn">Naar de actie</button>
                        </div>
                    </div>

                </a>
            </li>

            <li class="banners__item banners__item--2">
                <a class="banners__link">

                    <div class="banners__wrapper">

                        <div class="banners__content banners__content--2">
                            <h3 class="banners__subtitle banners__subtitle--2">Hoge korting op</h3>
                            <p class="banners__text">rugzakken en tassen</p>
                            <button class="banners__button banners__button--2 button">
                                <span class="banners__arrow blocks-promo__arrow">></span>
                            </button>
                        </div>

                        <div class="banners__image banners__image--2"></div>

                    </div>

                </a>
            </li>
        </ul>
    </div>

</div>

<script> 
 function updateTimer() {
    let future = Date.parse("Oct 2, 2022 11:30:00");
    let now = new Date();
    let diff = future - now;

    let days = Math.floor(diff / (1000 * 60 * 60 * 24));
    let hours = Math.floor(diff / (1000 * 60 * 60));
    let mins = Math.floor(diff / (1000 * 60));
    let secs = Math.floor(diff / 1000);

    let d = days;
    let h = hours - days * 24;
    let m = mins - hours * 60;
    let s = secs - mins * 60;

    document.getElementById("demo").innerHTML =
        "<div>" +
        d +
        "<span>days</span></div>" +
        "<div>" +
        h +
        "<span>hours</span></div>" +
        "<div>" +
        m +
        "<span>minutes</span></div>" +
        "<div>" +
        s +
        "<span>seconds</span></div>";
}
setInterval("updateTimer()", 1000);

if (diff < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "EXPIRED";
}

</script>