<div class="banners">
    <div class="container">
        <ul class="banners__list">

            <li class="banners__item banners__item--1">
                <a class="banners__link">

                    <h2 class="banners__title">Dagdeal
                    </h2>

                    <div class="banners__wrapper">
                        <div class="banners__image">
                        </div>

                        <div class="banners__content">
                            <h3 class="banners__subtitle">Tot 30% korting op diervoeding & dierbenodigdheden*</h3>
                            <button class="banners__button">Naar de actie</button>
                        </div>
                    </div>

                </a>
            </li>

            <li class="banners__item banners__item--2">
                <a class="banners__link">
                    <h3 class="banners__subtitle">Hoge korting op monitoren</h3>
                    <p class="banners__text">Ga voor een soepele start</p>
                    <button class="banners__button blocks-promo__button">
                        <span class="banners__arrow blocks-promo__arrow">></span>
                    </button>
                </a>
            </li>
        </ul>

    </div>
</div>