<?php
/**
 * Copyright © Elogic. All rights reserved.
 * See https://elogic.co for license details.
 */
?>
<div class="blocks-promo">
    <a
        href="{{store url="
        "}}collections/yoga-new.html"
        class="block-promo home-main">
        <img
            class="blocks-promo__banner"
            src="{{view url="images/blocks-promo-images/blocks-promo-banner.jpg"}}" alt="" />
    </a>
</div>

<ul class="blocks-promo__list">

    <li class="blocks-promo__item">
        <a class="blocks-promo__link">
            <div class="blocks-promo__box blocks-promo__box--1">

                <div class="blocks-promo__content">
                    <span class="blocks-promo__text">
                        <h2 class="blocks-promo__title">
                            Nu Select-korting
                        </h2>
                        <p class="blocks-promo__txt">
                            op instant camera's
                        </p>
                    </span>
                </div>

                <div
                    class="blocks-promo__image"
                    style="background-image: url('{{view url='images/blocks-promo-images/blocks-promo-image-1.jpg'}}')"></div>

                <button class="blocks-promo__button button">
                    <span class="blocks-promo__arrow">
                        >
                    </span>
                </button>

            </a>
        </div>
    </li>

    <li class="blocks-promo__item">
        <a class="blocks-promo__link">
            <div class="blocks-promo__box blocks-promo__box--2">

                <div class="blocks-promo__content">
                    <span class="blocks-promo__text">
                        <h2 class="blocks-promo__title">
                            Tot 20% Select-korting
                        </h2>
                        <p class="blocks-promo__txt">
                            op spellen
                        </p>
                    </span>
                </div>

                <div
                    class="blocks-promo__image"
                    style="background-image: url('{{view url='images/blocks-promo-images/blocks-promo-image-2.jpg'}}')"></div>

                <button class="blocks-promo__button button">
                    <span class="blocks-promo__arrow">
                        >
                    </span>
                </button>

            </a>
        </div>
    </li>

    <li class="blocks-promo__item">
        <a class="blocks-promo__link">
            <div class="blocks-promo__box blocks-promo__box--3">

                <div class="blocks-promo__content">
                    <span class="blocks-promo__text">
                        <h2 class="blocks-promo__title">
                            Tot 20% Select-korting
                        </h2>
                        <p class="blocks-promo__txt">
                            op instant camera's
                        </p>
                    </span>
                </div>

                <div
                    class="blocks-promo__image"
                    style="background-image: url('{{view url='images/blocks-promo-images/blocks-promo-image-3.jpg'}}')"></div>
                <button class="blocks-promo__button button">
                    <span class="blocks-promo__arrow">
                        >
                    </span>
                </button>

            </a>
        </div>
    </li>

    <li class="blocks-promo__item">
        <a class="blocks-promo__link">
            <div class="blocks-promo__box blocks-promo__box--4">

                <div class="blocks-promo__content">
                    <span class="blocks-promo__text">
                        <h2 class="blocks-promo__title">
                            Select-Deals op
                        </h2>
                        <p class="blocks-promo__txt">
                            koptelefoons en speakers
                        </p>
                    </span>
                </div>

                <div class="blocks-promo__image"
                  style="background-image: url('{{view url='images/blocks-promo-images/blocks-promo-image-4.jpg'}}')">
                </div>
                    <button class="blocks-promo__button button">
                        <span class="blocks-promo__arrow">
                            >
                        </span>
                    </button>

                </div>
            </a>
        </li>
    </ul>
</div>