<div class="filmstrip-viewport">
    <div class="filmstrip-viewport__box">
        <div class="filmstrip-viewport__inner">
            <h2 class="filmstrip-viewport__title">
                Populair binnen boeken
            </h2>
            <p class="filmstrip-viewport__text">
                Bekijk al je persoonlijke aanbevelingen
            </p>
        </div>
        <div class="filmstrip-viewport__content">
          <ul class="filmstrip-viewport__list">
            <a class="filmstrip-viewport__link">
              <img class="filmstrip-viewport__image">
              <p class="filmstrip-viewport__txt"></p>
            </a>
            <p class="filmstrip-viewport__price"></p>

          </ul>
        </div>
    </div>
</div>