<div class="gifts-everyone">
    <div class="container">
      <div class="gifts-everyone__box">
        <h2 class="gifts-everyone__title">
            Cadeaus voor iedereen
        </h2>
        <a class="gifts-everyone__txt a-btn">Alle cadeaus</a>
      </div>

        <ul class="gifts-everyone__list">
            <li class="gifts-everyone__item">
                <a class="gifts-everyone__link" href="#">
                    <div class="gifts-everyone__image" style="background-image: url('<?php echo $this->getViewFileUrl("images/gifts-everyone/1.jpg") ?>');"></div>
                    <p class="gifts-everyone__text a-btn">De cadeauwinkel</p>
                </a>
            </li>

            <li class="gifts-everyone__item">
                <a class="gifts-everyone__link" href="#">
                    <div class="gifts-everyone__image" style="background-image: url('<?php echo $this->getViewFileUrl("images/gifts-everyone/2.jpg") ?>');"></div>
                    <p class="gifts-everyone__text a-btn">Kids cadeaupagina</p>
                </a>
            </li>

            <li class="gifts-everyone__item">
                <a class="gifts-everyone__link" href="#">
                    <div class="gifts-everyone__image" style="background-image: url('<?php echo $this->getViewFileUrl("images/gifts-everyone/3.jpg") ?>');"></div>
                    <p class="gifts-everyone__text a-btn">Verrassende cadeaus</p>
                </a>
            </li>

            <li class="gifts-everyone__item">
                <a class="gifts-everyone__link" href="#">
                    <div class="gifts-everyone__image" style="background-image: url('<?php echo $this->getViewFileUrl("images/gifts-everyone/4.jpg") ?>');"></div>
                    <p class="gifts-everyone__text a-btn">Verjaardag</p>
                </a>
            </li>
        </ul>
    </div>
</div>