<div class="header-top">
    <div class="container">
        <div class="header-top__inner">
            <ul class="header-top__list">
                <li class="header-top__item">
                    <a class="header-top__link a-btn" href="#">
                        <strong>Gratis</strong>
                        verzending vanaf 20,-
                    </a>
                </li>

                <li class="header-top__item">
                    <a class="header-top__link a-btn" href="#">
                        Bezorging dezelfde dag, 's avonds of in het weekend*
                    </a>
                </li>

                <li class="header-top__item a-btn">
                    <a class="header-top__link" href="#">
                        <strong>Gratis</strong>
                        retourneren
                    </a>
                </li>
            </ul>

            <div class="header-top__text">
                <a class="header-top__txt a-btn">
                    <strong>Select</strong>
                    Ontdek nu de 4 voordelen</a>
            </div>
        </div>
    </div>
</div>