<div class="interesting">
    <div class="container">

        <h2 class="interesting__title">
          Ook interessant
        </h2>


        <ul class="interesting__list">

            <li class="interesting__item">
                <a class="interesting__link" href="#">
                    <div class="interesting__image interesting__image--1"></div>
                    <h3 class="interesting__subtitle a-btn">Een perfect resultaat vanuit huis</h3>
                    <p class="interestinf__text a-btn">met Syoss haarkleuring</p>
                </a>
            </li>

            <li class="interesting__item">
                <a class="interesting__link" href="#">
                    <div class="interesting__image interesting__image--2"></div>
                    <h3 class="interesting__subtitle a-btn">Ga voor een complete make-up look</h3>
                    <p class="interestinf__text a-btn">met Max Factor make-up</p>
                </a>
            </li>

            <li class="interesting__item">
                <a class="interesting__link" href="#">
                    <div class="interesting__image interesting__image--3"></div>
                    <h3 class="interesting__subtitle a-btn">Lonneke Nooteboom</h3>
                    <p class="interestinf__text a-btn">Chef Mode</p>
                </a>
            </li>

        </ul>
    </div>
</div>