<?php
/**
 * Copyright © Elogic. All rights reserved.
 * See https://elogic.co for license details.
 */
?>
<div class="navigation-footer">
    <div class="container">
        <div class="navigation-footer__box">
            <h2 class="navigation-footer__title">Ontdek alles bij bol.com</h2>
        </div>

        <div class="navigation-footer__content">
            <ul class="navigation-footer__list">

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Boeken</h3>
                    <a class="navigation-footer__link a-btn">Boeken</a>
                    <a class="navigation-footer__link a-btn">Nederlandstalige boeken</a>
                    <a class="navigation-footer__link a-btn">Engelstalige boeken</a>
                    <a class="navigation-footer__link a-btn">E-books</a>
                    <a class="navigation-footer__link a-btn">E-readers</a>
                    <a class="navigation-footer__link a-btn">Kobo Plus abonnement</a>
                    <a class="navigation-footer__link a-btn">Tweedehands boeken</a>
                    <a class="navigation-footer__link a-btn">Luisterboeken</a>
                    <a class="navigation-footer__link a-btn">Studieboeken</a>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Muziek, Film & Games</h3>
                    <a class="navigation-footer__link a-btn">Muziek</a>
                    <a class="navigation-footer__link a-btn">Dvd</a>
                    <a class="navigation-footer__link a-btn">Blu-ray</a>
                    <a class="navigation-footer__link a-btn">TV-series</a>
                    <a class="navigation-footer__link a-btn">Games</a>
                    <a class="navigation-footer__link a-btn">Consoles & accessoires</a>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Sport, Outdoor & Reizen</h3>
                    <a class="navigation-footer__link a-btn">Sport</a>
                    <a class="navigation-footer__link a-btn">Sportkleding</a>
                    <a class="navigation-footer__link a-btn">Kamperen & Outdoor</a>
                    <a class="navigation-footer__link a-btn">Reisbagage</a>
                </li>
            </ul>

            <ul class="navigation-footer__list">
                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Computer & Elektronica</h3>
                    <a class="navigation-footer__link a-btn">Computer</a>
                    <a class="navigation-footer__link a-btn">Telefonie</a>
                    <a class="navigation-footer__link a-btn">Tablets</a>
                    <a class="navigation-footer__link a-btn">Huishoudelijke apparaten</a>
                    <a class="navigation-footer__link a-btn">Keukenapparaten</a>
                    <a class="navigation-footer__link a-btn">Camera's</a>
                    <a class="navigation-footer__link a-btn">Wearables</a>
                    <a class="navigation-footer__link a-btn">Navigatie</a>
                    <a class="navigation-footer__link a-btn">Televisies</a>
                    <a class="navigation-footer__link a-btn">Audio & Hifi</a>
                    <a class="navigation-footer__link a-btn">Persoonlijke verzorging</a>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Kantoor & School</h3>
                    <a class="navigation-footer__link a-btn">Kantoor & School</a>
                    <a class="navigation-footer__link a-btn">Kantoorspullen</a>
                    <a class="navigation-footer__link a-btn">Schoolspullen</a>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Speelgoed & Hobby</h3>
                    <a class="navigation-footer__link a-btn">Speelgoed</a>
                    <a class="navigation-footer__link a-btn">Hobby & Creatief</a>
                    <a class="navigation-footer__link a-btn">Buitenspeelgoed</a>
                    <a class="navigation-footer__link a-btn">Verkleedkleding</a>
                </li>
            </ul>

            <ul class="navigation-footer__list">

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Koken & Tafelen</h3>
                    <a class="navigation-footer__link a-btn">Koken & Tafelen</a>
                    <a class="navigation-footer__link a-btn">Barbecues</a>
                    <a class="navigation-footer__link a-btn">Pannen</a>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Huishouden</h3>
                    <a class="navigation-footer__link a-btn">Huishouden</a>
                    <a class="navigation-footer__link a-btn">Prullenbakken</a>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Tuin</h3>
                    <a class="navigation-footer__link a-btn">Tuin</a>
                    <a class="navigation-footer__link a-btn">Tuinmeubelen</a>
                    <a class="navigation-footer__link a-btn">Tuingereedschap</a>
                </li>

                                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Dier</h3>
                    <a class="navigation-footer__link a-btn">Dier</a>
                    <a class="navigation-footer__link a-btn">Hond</a>
                    <a class="navigation-footer__link a-btn">Katten</a>
                    <a class="navigation-footer__link a-btn">Paard & Ruiter</a>
                    <a class="navigation-footer__link a-btn">E-readers</a>
                    <a class="navigation-footer__link a-btn">Knaagdieren</a>
                    <a class="navigation-footer__link a-btn">Vissen</a>
                    <a class="navigation-footer__link a-btn">Reptielen</a>
                    <a class="navigation-footer__link a-btn">Vogels</a>
                </li>

            </ul>

            <ul class="navigation-footer__list">

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Wonen</h3>
                    <a class="navigation-footer__link a-btn">Wonen</a>
                    <a class="navigation-footer__link a-btn">Meubels</a>
                    <a class="navigation-footer__link a-btn">Beddengoed</a>
                    <a class="navigation-footer__link a-btn">Verlichting</a>
                    <a class="navigation-footer__link a-btn">Woonaccessoires</a>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Klussen</h3>
                    <a class="navigation-footer__link a-btn">Klussen</a>
                    <a class="navigation-footer__link a-btn">Elektrisch gereedschap</a>
                    <a class="navigation-footer__link a-btn">Werkkleding & Bescherming</a>
                    <a class="navigation-footer__link a-btn">Verfspullen</a>
                    <a class="navigation-footer__link a-btn">Behang</a>
                    <a class="navigation-footer__link a-btn">Bouwmaterialen</a>
                    <a class="navigation-footer__link a-btn">Opbergen & Verhuizen</a>
                    <a class="navigation-footer__link a-btn">Sanitair</a>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Mooi & Gezond</h3>
                    <a class="navigation-footer__link a-btn">Mooi & Gezond</a>
                    <a class="navigation-footer__link a-btn">Make-up</a>
                    <a class="navigation-footer__link a-btn">Parfum</a>
                    <a class="navigation-footer__link a-btn">Verzorging</a>
                    <a class="navigation-footer__link a-btn">Gezondheid</a>
                    <a class="navigation-footer__link a-btn">Erotiek</a>
                </li>
            </ul>

            <ul class="navigation-footer__list">
                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Damesmode</h3>
                    <a class="navigation-footer__link a-btn">Damesmode</a>
                    <a class="navigation-footer__link a-btn">Dameskleding</a>
                    <a class="navigation-footer__link a-btn">Dames schoenen</a>
                    <a class="navigation-footer__link a-btn">Lingerie</a>
                    <a class="navigation-footer__link a-btn">Keukenapparaten</a>
                    <a class="navigation-footer__link a-btn">Dames accessoires</a>
                    <a class="navigation-footer__link a-btn">Dames sieraden & horloges</a>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Herenmode</h3>
                    <a class="navigation-footer__link a-btn">Herenmode</a>
                    <a class="navigation-footer__link a-btn">Herenkleding</a>
                    <a class="navigation-footer__link a-btn">Heren schoenen</a>
                    <a class="navigation-footer__link a-btn">Heren ondergoed</a>
                    <a class="navigation-footer__link a-btn">Heren accessoires</a>
                    <a class="navigation-footer__link a-btn">Heren sieraden & horloges</a>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Baby & Kind</h3>
                    <a class="navigation-footer__link a-btn">Babykleding</a>
                    <a class="navigation-footer__link a-btn">Babyartikelen</a>
                    <a class="navigation-footer__link a-btn">Kinderkleding</a>
                    <a class="navigation-footer__link a-btn">Jongenskleding</a>
                    <a class="navigation-footer__link a-btn">Meisjeskleding</a>
                </li>
            </ul>

            <ul class="navigation-footer__list">

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Dranken & Delicatessen</h3>
                    <a class="navigation-footer__link a-btn">Koffie</a>
                    <a class="navigation-footer__link a-btn">Thee</a>
                    <a class="navigation-footer__link a-btn">Chocolade</a>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Auto & Motor</h3>
                    <a class="navigation-footer__link a-btn">Auto & Motor</a>
                    <a class="navigation-footer__link a-btn">Auto-accessoires</a>
                    <a class="navigation-footer__link a-btn">Auto-onderhoud</a>
                    <a class="navigation-footer__link a-btn">Auto-onderdelen</a>
                    <a class="navigation-footer__link a-btn">Motoraccessoires</a>
                    <a class="navigation-footer__link a-btn">Motorkleding</a>
                    <a class="navigation-footer__link a-btn">Motoronderhoud & -onderdelen</a>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Inspiratie</h3>
                    <a class="navigation-footer__link a-btn">Lees Magazine</a>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Cadeaubonnen</h3>
                    <a class="navigation-footer__link a-btn">Cadeaubonnen</a>
                </li>
            </ul>

        </div>
    </div>
</div>