<div class="navigation-footer">
    <div class="container">
        <div class="navigation-footer__box">
            <ul class="navigation-footer__list">

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Boeken</h3>
                    <p class="navigation-footer__text">Boeken</p>
                    <p class="navigation-footer__text">Nederlandstalige boeken</p>
                    <p class="navigation-footer__text">Engelstalige boeken</p>
                    <p class="navigation-footer__text">E-books</p>
                    <p class="navigation-footer__text">E-readers</p>
                    <p class="navigation-footer__text">Kobo Plus abonnement</p>
                    <p class="navigation-footer__text">Tweedehands boeken</p>
                    <p class="navigation-footer__text">Luisterboeken</p>
                    <p class="navigation-footer__text">Studieboeken</p>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle"></h3>
                    <p class="navigation-footer__text"></p>
                    <p class="navigation-footer__text"></p>
                    <p class="navigation-footer__text"></p>
                    <p class="navigation-footer__text"></p>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Muziek, Film & Games</h3>
                    <p class="navigation-footer__text">Muziek</p>
                    <p class="navigation-footer__text">Dvd</p>
                    <p class="navigation-footer__text">Blu-ray</p>
                    <p class="navigation-footer__text">TV-series</p>
                </li>

                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Sport, Outdoor & Reizen</h3>
                    <p class="navigation-footer__text">Sport</p>
                    <p class="navigation-footer__text">Sportkleding</p>
                    <p class="navigation-footer__text">Kamperen & Outdoor</p>
                    <p class="navigation-footer__text">Reisbagage</p>
                </li>
            </ul>

            <ul class="navigation-footer__list">
                <li class="navigation-footer__item">
                    <h3 class="naigation-footer__subtitle">Computer & Elektronica</h3>
                    <p class="navigation-footer__text">Computer</p>
                    <p class="navigation-footer__text">Telefonie</p>
                    <p class="navigation-footer__text">Tablets</p>
                    <p class="navigation-footer__text">Huishoudelijke apparaten</p>
                    <p class="navigation-footer__text">Keukenapparaten</p>
                    <p class="navigation-footer__text">Camera's</p>
                    <p class="navigation-footer__text">Wearables</p>
                    <p class="navigation-footer__text">Navigatie</p>
                    <p class="navigation-footer__text">Televisies</p>
                    <p class="navigation-footer__text">Audio & Hifi</p>
                    <p class="navigation-footer__text">Persoonlijke verzorging</p>
                </li>
            </ul>
        </div>
    </div>
</div>