<div class="under-navigation">
    <div class="container">
        <div class="under-navigation__box">
            <ul class="under-navigation__list">
                <li class="under-navigation__item">
                    <a class="under-navigation__link a-btn">
                        Bollebozen Letterpretpakket
                    </a>
                </li>

                <li class="under-navigation__item">
                    <a class="under-navigation__link a-btn">
                        Pride
                    </a>
                </li>

                <li class="under-navigation__item">
                    <a class="under-navigation__link a-btn">
                        Elektronica Acties
                    </a>
                </li>

                <li class="under-navigation__item">
                    <a class="under-navigation__link a-btn">
                        Alles voor je vakantie
                    </a>
                </li>

                <li class="under-navigation__item">
                    <a class="under-navigation__link-deel a-btn">
                        Héél véél Select-Deals
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>