<div class="under-navigation">
    <div class="under-navigation__box">
        <ul class="under-navigation__list">
            <li class="under-navigation__item">
                <a class="under-navigation__link">
                    Bollebozen Letterpretpakket
                </a>
            </li>

            <li class="under-navigation__item">
                <a class="under-navigation__link">
                    Pride
                </a>
            </li>

            <li class="under-navigation__item">
                <a class="under-navigation__link">
                    Elektronica Acties
                </a>
            </li>

            <li class="under-navigation__item">
                <a class="under-navigation__link">
                    Alles voor je vakantie
                </a>
            </li>

            <li class="under-navigation__item">
                <a class="under-navigation__link-deel">
                    Héél véél Select-Deals
                </a>
            </li>
        </ul>
    </div>
</div>