<?php
/**
 * Copyright © Elogic. All rights reserved.
 * See https://elogic.co for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter__box toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sortering')) ?></label>
    <button class="toolbar-sorter__button-info sorter-btn-info" id="sorter-open-btn" type="button"
            data-mage-init='{"toggleAdvanced": {"selectorsToggleClass": "active", "toggleContainers": ".modal, #overlay"}}'>
        <svg class="toolbar-sorter__icon" viewBox="0 0 14 14">
            <path fill-rule="evenodd"
                  d="M7 14A7 7 0 117 0a7 7 0 010 14zm-.033-1a6 6 0 100-12 6 6 0 000 12zm-.464-6.984a.512.512 0 01.509-.516h-.024c.283 0 .514.228.515.516l.027 3.968a.512.512 0 01-.509.516h.024a.516.516 0 01-.515-.516l-.027-3.968zM7.031 4.5a.5.5 0 110-1 .5.5 0 010 1z"></path>
        </svg>
    </button>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) : ?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) : ?>
                    selected="selected"
                <?php endif; ?>
            >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc') : ?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
            <img src="images/toolbar-icons/grid.less" alt="">
        </a>
    <?php else : ?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
    <div class="modal">

        <button id="toolbar-modal__close" class="modal-close"
            data-mage-init='{"toggleAdvanced": {"selectorsToggleClass": "active", "toggleContainers": ".modal, #overlay"}}'>
            &times;
        </button>

        <h2 id="toolbar-modal__title"><?= __('Hoe sorteren werkt') ?></h2>
        <p id="toolbar-modal__text">
          <?= __('Artikelen hebben vaak meerdere verkopers. Je ziet per zoekresultaat de verkoper die het beste scoort op leverbelofte, prijs en prestatiescore. Daarnaast sorteren we standaard alle resultaten op populariteit, maar je kunt deze ook zelf sorteren:') ?>
        </p>

    <ul id="toolbar-modal__list">
    <li id="toolbar-modal__item">
      <h3 id="toolbar-modal__subtitle"><?= __('Populariteit van de artikelen') ?>
      </h3>
      <p id="toolbar-modal__item-text">
          <?= __('Hiervoor kijken we op verschillende manieren naar hoeveel interesse er is in een artikel. Tussen de
          resultaten kunnen ook gesponsorde artikelen* verschijnen.') ?>
      </p>
    </li>

      <li id="toolbar-modal__item">
      <h3 id="toolbar-modal__subtitle"><?= __('Prijs') ?></h3>
      <p id="toolbar-modal__item-text">
          <?= __('Van laag naar hoog of van hoog naar laag.') ?>
      </p>
  </li>

    <li id="toolbar-modal__item">
      <h3 id="toolbar-modal__subtitle"><?= __('Nieuw op bol.com') ?></h3>
      <p id="toolbar-modal__item-text">
          <?= __('Wat nieuw is op bol.com staat bovenaan.') ?>
      </p>
  </li>

  <li id="toolbar-modal__item">
      <h3 id="toolbar-modal__subtitle"><?= __('Beoordeling') ?></h3>
      <p id="toolbar-modal__item-text">
          <?= __('Artikelen met de beste reviews komen eerst. We kijken per artikel wat de score is, hoeveel reviews er zijn en hoe nieuw de reviews zijn.') ?>
      </p>
  </li>

    <li id="toolbar-modal__item">
      <h3 id="toolbar-modal__subtitle"><?= __('Meest gewild op verlanglijstjes') ?></h3>
      <p id="toolbar-modal__item-text">
          <?= __('Hoe vaker bewaard, hoe hoger het staat.') ?>
      </p>
  </li>

    <li id="toolbar-modal__popup-bottom">
    <h3 id="toolbar-modal__subtitle"><?= __('* Wat zijn gesponsorde artikelen?') ?></h3>
    <p id="toolbar-modal__item-text"><?= __('Verkopers kunnen tegen betaling een artikel meer op laten vallen. Het staat dan hoger tussen de resultaten.') ?>
    </p>
    </li>

  </ul>
</div>
    
<div id="overlay"
         data-mage-init='{"toggleAdvanced": {"selectorsToggleClass": "active", "baseToggleClass": "", "toggleContainers": ".modal, #overlay"}}'></div>
</div>
