<?php
/**
 * Copyright © Elogic. All rights reserved.
 * See https://elogic.co for license details.
 */

/* @var \Magento\Wishlist\Block\Link $block */
?>

<ul class="wishlist__list">
  <li class="link wishlist" data-bind="scope: 'wishlist'">
      <a class="add wishlist" <?= /* @noEscape */ $block->getLinkAttributes() ?>>
      
      <img class="wishlist__image" src="<?= $block->getViewFileUrl('images/heart.svg'); ?>" alt="wihlist image" width="21" height="21" />

          <!-- ko if: wishlist().counter -->
          <span class="counter qty" data-bind="text: wishlist().items.length"></span>
          <!-- /ko -->
      </a>
  </li>
</ul>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>